### ISSUE TITLE
threading error / fft error

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/codec2-FreeDATA#48]
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dj2ls/FreeDV-JATE/modem.py", line 425, in receive
    self.calculate_fft(data_in)
  File "/home/dj2ls/FreeDV-JATE/modem.py", line 608, in calculate_fft
    data = fft(data_in)
  File "/home/dj2ls/.local/lib/python3.9/site-packages/scipy/fft/_backend.py", line 23, in __ua_function__
    return fn(*args, **kwargs)
  File "/home/dj2ls/.local/lib/python3.9/site-packages/scipy/fft/_pocketfft/basic.py", line 26, in c2c
    raise ValueError("invalid number of data points ({0}) specified"
ValueError: invalid number of data points (0) specified

**Comment by DJ2LS** [comment]
https://stackoverflow.com/a/48015264
