### ISSUE TITLE
static.HAMLIB_MODE = rigctld.get_mode()[0] TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/codec2-FreeDATA#64]
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dn2ls/codec2-FreeDATA/tnc/modem.py", line 443, in receive
    self.get_radio_stats()
  File "/home/dn2ls/codec2-FreeDATA/tnc/modem.py", line 642, in get_radio_stats
    static.HAMLIB_MODE = rigctld.get_mode()[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by DJ2LS** [comment]
Solved with moving back to Hamlib python binding
