### ISSUE TITLE
    self.my_rig.set_ptt(self.hamlib_ptt_type, 1) AttributeError: 'RF' object has no attribute 'my_rig'

### ISSUE THREAD

**Issue by DJ2LS** [DJ2LS/codec2-FreeDATA#65]
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dn2ls/codec2-FreeDATA/tnc/data_handler.py", line 544, in open_dc_and_transmit
    arq_transmit(data_out)
  File "/home/dn2ls/codec2-FreeDATA/tnc/data_handler.py", line 321, in arq_transmit
    modem.transmit_arq_burst()
  File "/home/dn2ls/codec2-FreeDATA/tnc/modem.py", line 278, in transmit_arq_burst
    self.my_rig.set_ptt(self.hamlib_ptt_type, 1)
AttributeError: 'RF' object has no attribute 'my_rig'

**Comment by DJ2LS** [comment]
Solved with moving back to Hamlib Python binding
